name: Déployer le site web

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v6

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v6

      - name: Installer PNPM
        uses: pnpm/action-setup@v6

      - name: Installer Node.JS v26
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"

      - name: Installer les dépendances
        run: pnpm ci

      - name: Construire le site web
        run: pnpm build

      - name: Téléverser les artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5